#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
edgecore,eap105)
	ucidef_set_led_default "power" "pwr" "green:system" "1"
	ucidef_set_led_netdev "wan" "wan" "orange:ethernet" "eth0" "rx tx"
	;;
emplus,wap7635)
	ucidef_set_led_default "ledb" "LEDB" "sys:blue" "on"
	ucidef_set_led_default "ledg" "LEDG" "sys:green" "off"
	ucidef_set_led_default "ledr" "LEDR" "sys:red" "off"
	;;
indio,um-325be)
	ucidef_set_led_default "power" "POWER" "led_power" "on"
	;;
sercomm,ap72tip-v4|\
sercomm,ap72tip)
	ucidef_set_led_default "power" "POWER" "blue:status" "on"
	ucidef_set_led_netdev "wan_link" "wan_link" "green:phy" "eth0" "link"
	ucidef_set_led_netdev "wan_act" "wan_act" "yellow:phy" "eth0" "rx tx"
	;;
sonicfi,rap7110c-341x|\
sonicfi,rap750e-h|\
sonicfi,rap750e-s|\
sonicfi,rap750w-311a)
	ucidef_set_led_default "power" "POWER" "pwm:blue" "on"
	;;
jdcloud,be6500)
	ucidef_set_led_netdev "WAN" "WAN" "led_green" "eth0"
	;;
jdcloud,er2|jdcloud,re-cs-08)
	ucidef_set_led_default "power" "POWER" "led_green" "1"
	# led-boot = &led_blue never gets switched off at boot ("connect" state only
	# touches the running LED), so the blue LED keeps the 100ms timer set during
	# preinit.  Force it off once /etc/init.d/led runs (START=96 > done=95).
	ucidef_set_led_default "boot" "BOOT" "led_blue" "0"
	ucidef_set_led_netdev "SFP" "SFP" "led_sfp" "eth0" "link tx rx"
	;;
esac

board_config_flush

exit 0
